local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

-- [[ Backgrounds ]] --

-- [[ Borders ]] --

-- [[ Fonts ]] --
LSM:Register("font", "ITC-Avant-Garde-Gothic", [[Interface\Addons\LMT\Fonts\ITC-Avant-Garde-Gothic.ttf]])
LSM:Register("font", "Montserrat-Medium", [[Interface\Addons\LMT\Fonts\Montserrat-Medium.ttf]])
LSM:Register("font", "Montserrat-Regular", [[Interface\Addons\LMT\Fonts\Montserrat-Regular.ttf]])
LSM:Register("font", "Montserrat-SemiBold", [[Interface\Addons\LMT\Fonts\Montserrat-SemiBold.ttf]])
LSM:Register("font", "Play-Bold", [[Interface\Addons\LMT\Fonts\Play-Bold.ttf]])
LSM:Register("font", "Play-Regular", [[Interface\Addons\LMT\Fonts\Play-Regular.ttf]])
LSM:Register("font", "Poppins-Medium", [[Interface\Addons\LMT\Fonts\Poppins-Medium.ttf]])
LSM:Register("font", "Poppins-Regular", [[Interface\Addons\LMT\Fonts\Poppins-Regular.ttf]])
LSM:Register("font", "Poppins-SemiBold", [[Interface\Addons\LMT\Fonts\Poppins-SemiBold.ttf]])

-- [[ Sounds ]] --
--Auction Info
LSM:Register("sound", "|cFF89eb34Coin-Alternate|r", [[Interface\Addons\LMT\Sounds\Coin-Alternate.ogg]])
LSM:Register("sound", "|cFF89eb34Coin-Alternate2|r", [[Interface\Addons\LMT\Sounds\Coin-Alternate2.ogg]])
LSM:Register("sound", "|cFF89eb34Coin-Big|r", [[Interface\Addons\LMT\Sounds\Coin-Big.ogg]])
LSM:Register("sound", "|cFF89eb34Coin-Normal|r", [[Interface\Addons\LMT\Sounds\Coin-Normal.ogg]])
LSM:Register("sound", "|cFF89eb34Coin-SemiNormal|r", [[Interface\Addons\LMT\Sounds\Coin-SemiNormal.ogg]])
LSM:Register("sound", "|cFF89eb34Coin-Sweet|r", [[Interface\Addons\LMT\Sounds\Coin-Sweet.ogg]])
-- Self Info
LSM:Register("sound", "|cFFebd634Clearcasting|r", [[Interface\Addons\LMT\Sounds\Clearcasting.ogg]])
-- General Info
LSM:Register("sound", "|cFFeb6234CR|r", [[Interface\Addons\LMT\Sounds\CR.ogg]])
LSM:Register("sound", "|cFFeb6234Dead|r", [[Interface\Addons\LMT\Sounds\Dead.ogg]])
-- Dungeon & Raid
LSM:Register("sound", "|cFFd408cd1|r", [[Interface\Addons\LMT\Sounds\1.ogg]])
LSM:Register("sound", "|cFFd408cd2|r", [[Interface\Addons\LMT\Sounds\2.ogg]])
LSM:Register("sound", "|cFFd408cd3|r", [[Interface\Addons\LMT\Sounds\3.ogg]])
LSM:Register("sound", "|cFFd408cd4|r", [[Interface\Addons\LMT\Sounds\4.ogg]])
LSM:Register("sound", "|cFFd408cd5|r", [[Interface\Addons\LMT\Sounds\5.ogg]])
LSM:Register("sound", "|cFFd408cd6|r", [[Interface\Addons\LMT\Sounds\6.ogg]])
LSM:Register("sound", "|cFFd408cd7|r", [[Interface\Addons\LMT\Sounds\7.ogg]])
LSM:Register("sound", "|cFFd408cd8|r", [[Interface\Addons\LMT\Sounds\8.ogg]])
LSM:Register("sound", "|cFFd408cd9|r", [[Interface\Addons\LMT\Sounds\9.ogg]])
LSM:Register("sound", "|cFFd408cd10|r", [[Interface\Addons\LMT\Sounds\10.ogg]])
LSM:Register("sound", "|cFFd408cdAdd|r", [[Interface\Addons\LMT\Sounds\Add.ogg]])
LSM:Register("sound", "|cFFd408cdAdds|r", [[Interface\Addons\LMT\Sounds\Adds.ogg]])
LSM:Register("sound", "|cFFd408cdAoE|r", [[Interface\Addons\LMT\Sounds\AoE.ogg]])
LSM:Register("sound", "|cFFd408cdAssist|r", [[Interface\Addons\LMT\Sounds\Assist.ogg]])
LSM:Register("sound", "|cFFd408cdAvoid|r", [[Interface\Addons\LMT\Sounds\Avoid.ogg]])
LSM:Register("sound", "|cFFd408cdBackup|r", [[Interface\Addons\LMT\Sounds\Backup.ogg]])
LSM:Register("sound", "|cFFd408cdBait|r", [[Interface\Addons\LMT\Sounds\Bait.ogg]])
LSM:Register("sound", "|cFFd408cdBeam|r", [[Interface\Addons\LMT\Sounds\Beam.ogg]])
LSM:Register("sound", "|cFFd408cdBehind|r", [[Interface\Addons\LMT\Sounds\Behind.ogg]])
LSM:Register("sound", "|cFFd408cdBloodlust|r", [[Interface\Addons\LMT\Sounds\Bloodlust.ogg]])
LSM:Register("sound", "|cFFd408cdBlue|r", [[Interface\Addons\LMT\Sounds\Blue.ogg]])
LSM:Register("sound", "|cFFd408cdBreak|r", [[Interface\Addons\LMT\Sounds\Break.ogg]])
LSM:Register("sound", "|cFFd408cdBuff|r", [[Interface\Addons\LMT\Sounds\Buff.ogg]])
LSM:Register("sound", "|cFFd408cdCC|r", [[Interface\Addons\LMT\Sounds\CC.ogg]])
LSM:Register("sound", "|cFFd408cdCenter|r", [[Interface\Addons\LMT\Sounds\Center.ogg]])
LSM:Register("sound", "|cFFd408cdChain|r", [[Interface\Addons\LMT\Sounds\Chain.ogg]])
LSM:Register("sound", "|cFFd408cdClear|r", [[Interface\Addons\LMT\Sounds\Clear.ogg]])
LSM:Register("sound", "|cFFd408cdCollect|r", [[Interface\Addons\LMT\Sounds\Collect.ogg]])
LSM:Register("sound", "|cFFd408cdDance|r", [[Interface\Addons\LMT\Sounds\Dance.ogg]])
LSM:Register("sound", "|cFFd408cdDebuff|r", [[Interface\Addons\LMT\Sounds\Debuff.ogg]])
LSM:Register("sound", "|cFFd408cdDispell|r", [[Interface\Addons\LMT\Sounds\Dispell.ogg]])
LSM:Register("sound", "|cFFd408cdDodge|r", [[Interface\Addons\LMT\Sounds\Dodge.ogg]])
LSM:Register("sound", "|cFFd408cdDont Move|r", [[Interface\Addons\LMT\Sounds\Dont Move.ogg]])
LSM:Register("sound", "|cFFd408cdDot|r", [[Interface\Addons\LMT\Sounds\Dot.ogg]])
LSM:Register("sound", "|cFFd408cdDrop|r", [[Interface\Addons\LMT\Sounds\Drop.ogg]])
LSM:Register("sound", "|cFFd408cdEnter|r", [[Interface\Addons\LMT\Sounds\Enter.ogg]])
LSM:Register("sound", "|cFFd408cdEscort|r", [[Interface\Addons\LMT\Sounds\Escort.ogg]])
LSM:Register("sound", "|cFFd408cdExit|r", [[Interface\Addons\LMT\Sounds\Exit.ogg]])
LSM:Register("sound", "|cFFd408cdFixate|r", [[Interface\Addons\LMT\Sounds\Fixate.ogg]])
LSM:Register("sound", "|cFFd408cdFront|r", [[Interface\Addons\LMT\Sounds\Front.ogg]])
LSM:Register("sound", "|cFFd408cdGate|r", [[Interface\Addons\LMT\Sounds\Gate.ogg]])
LSM:Register("sound", "|cFFd408cdGather|r", [[Interface\Addons\LMT\Sounds\Gather.ogg]])
LSM:Register("sound", "|cFFd408cdGreen|r", [[Interface\Addons\LMT\Sounds\Green.ogg]])
LSM:Register("sound", "|cFFd408cdHealcd|r", [[Interface\Addons\LMT\Sounds\Healcd.ogg]])
LSM:Register("sound", "|cFFd408cdHide|r", [[Interface\Addons\LMT\Sounds\Hide.ogg]])
LSM:Register("sound", "|cFFd408cdHigh Energy|r", [[Interface\Addons\LMT\Sounds\High Energy.ogg]])
LSM:Register("sound", "|cFFd408cdHigh Stacks|r", [[Interface\Addons\LMT\Sounds\High Stacks.ogg]])
LSM:Register("sound", "|cFFd408cdImmunity|r", [[Interface\Addons\LMT\Sounds\Immunity.ogg]])
LSM:Register("sound", "|cFFd408cdIn|r", [[Interface\Addons\LMT\Sounds\In.ogg]])
LSM:Register("sound", "|cFFd408cdInterrupt|r", [[Interface\Addons\LMT\Sounds\Interrupt.ogg]])
LSM:Register("sound", "|cFFd408cdIntermission|r", [[Interface\Addons\LMT\Sounds\Intermission.ogg]])
LSM:Register("sound", "|cFFd408cdInvisibility|r", [[Interface\Addons\LMT\Sounds\Invisibility.ogg]])
LSM:Register("sound", "|cFFd408cdKnock|r", [[Interface\Addons\LMT\Sounds\Knock.ogg]])
LSM:Register("sound", "|cFFd408cdLeft|r", [[Interface\Addons\LMT\Sounds\Left.ogg]])
LSM:Register("sound", "|cFFd408cdLinked|r", [[Interface\Addons\LMT\Sounds\Linked.ogg]])
LSM:Register("sound", "|cFFd408cdMelee|r", [[Interface\Addons\LMT\Sounds\Melee.ogg]])
LSM:Register("sound", "|cFFd408cdMove|r", [[Interface\Addons\LMT\Sounds\Move.ogg]])
LSM:Register("sound", "|cFFd408cdNext|r", [[Interface\Addons\LMT\Sounds\Next.ogg]])
LSM:Register("sound", "|cFFd408cdOrange|r", [[Interface\Addons\LMT\Sounds\Orange.ogg]])
LSM:Register("sound", "|cFFd408cdOrb|r", [[Interface\Addons\LMT\Sounds\Orb.ogg]])
LSM:Register("sound", "|cFFd408cdOut|r", [[Interface\Addons\LMT\Sounds\Out.ogg]])
LSM:Register("sound", "|cFFd408cdOverlap|r", [[Interface\Addons\LMT\Sounds\Overlap.ogg]])
LSM:Register("sound", "|cFFd408cdPhase2|r", [[Interface\Addons\LMT\Sounds\Phase2.ogg]])
LSM:Register("sound", "|cFFd408cdPhase3|r", [[Interface\Addons\LMT\Sounds\Phase3.ogg]])
LSM:Register("sound", "|cFFd408cdPots|r", [[Interface\Addons\LMT\Sounds\Pots.ogg]])
LSM:Register("sound", "|cFFd408cdPurple|r", [[Interface\Addons\LMT\Sounds\Purple.ogg]])
LSM:Register("sound", "|cFFd408cdRange|r", [[Interface\Addons\LMT\Sounds\Range.ogg]])
LSM:Register("sound", "|cFFd408cdReady|r", [[Interface\Addons\LMT\Sounds\Ready.ogg]])
LSM:Register("sound", "|cFFd408cdRed|r", [[Interface\Addons\LMT\Sounds\Red.ogg]])
LSM:Register("sound", "|cFFd408cdReflect|r", [[Interface\Addons\LMT\Sounds\Reflect.ogg]])
LSM:Register("sound", "|cFFd408cdRight|r", [[Interface\Addons\LMT\Sounds\Right.ogg]])
LSM:Register("sound", "|cFFd408cdSelfcd|r", [[Interface\Addons\LMT\Sounds\Selfcd.ogg]])
LSM:Register("sound", "|cFFd408cdSoak|r", [[Interface\Addons\LMT\Sounds\Soak.ogg]])
LSM:Register("sound", "|cFFd408cdSoon|r", [[Interface\Addons\LMT\Sounds\Soon.ogg]])
LSM:Register("sound", "|cFFd408cdSpawn|r", [[Interface\Addons\LMT\Sounds\Spawn.ogg]])
LSM:Register("sound", "|cFFd408cdSpellsteal|r", [[Interface\Addons\LMT\Sounds\Spellsteal.ogg]])
LSM:Register("sound", "|cFFd408cdSplit|r", [[Interface\Addons\LMT\Sounds\Split.ogg]])
LSM:Register("sound", "|cFFd408cdSpread|r", [[Interface\Addons\LMT\Sounds\Spread.ogg]])
LSM:Register("sound", "|cFFd408cdStack|r", [[Interface\Addons\LMT\Sounds\Stack.ogg]])
LSM:Register("sound", "|cFFd408cdStop|r", [[Interface\Addons\LMT\Sounds\Stop.ogg]])
LSM:Register("sound", "|cFFd408cdStopcast|r", [[Interface\Addons\LMT\Sounds\Stopcast.ogg]])
LSM:Register("sound", "|cFFd408cdSwitch|r", [[Interface\Addons\LMT\Sounds\Switch.ogg]])
LSM:Register("sound", "|cFFd408cdTargeted|r", [[Interface\Addons\LMT\Sounds\Targeted.ogg]])
LSM:Register("sound", "|cFFd408cdTaunt|r", [[Interface\Addons\LMT\Sounds\Taunt.ogg]])
LSM:Register("sound", "|cFFd408cdTransition|r", [[Interface\Addons\LMT\Sounds\Transition.ogg]])
LSM:Register("sound", "|cFFd408cdTrap|r", [[Interface\Addons\LMT\Sounds\Trap.ogg]])
LSM:Register("sound", "|cFFd408cdTurn|r", [[Interface\Addons\LMT\Sounds\Turn.ogg]])
LSM:Register("sound", "|cFFd408cdYellow|r", [[Interface\Addons\LMT\Sounds\Yellow.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\LMT\Sounds\01.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\LMT\Sounds\02.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\LMT\Sounds\03.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\LMT\Sounds\04.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\LMT\Sounds\05.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\LMT\Sounds\06.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\LMT\Sounds\07.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\LMT\Sounds\08.ogg]])

-- [[ Statusbars ]] --
LSM:Register("statusbar", "Atrocity", [[Interface\Addons\LMT\Statusbars\Atrocity.tga]])
LSM:Register("statusbar", "ElvUI A", [[Interface\Addons\LMT\Statusbars\ElvUI A.tga]])
LSM:Register("statusbar", "ElvUI B", [[Interface\Addons\LMT\Statusbars\ElvUI B.tga]])
LSM:Register("statusbar", "ElvUI C", [[Interface\Addons\LMT\Statusbars\ElvUI C.tga]])
LSM:Register("statusbar", "ElvUI D", [[Interface\Addons\LMT\Statusbars\ElvUI D.tga]])
LSM:Register("statusbar", "ElvUI E", [[Interface\Addons\LMT\Statusbars\ElvUI E.tga]])
LSM:Register("statusbar", "ElvUI F", [[Interface\Addons\LMT\Statusbars\ElvUI F.tga]])
LSM:Register("statusbar", "ElvUI G", [[Interface\Addons\LMT\Statusbars\ElvUI G.tga]])
LSM:Register("statusbar", "ElvUI H", [[Interface\Addons\LMT\Statusbars\ElvUI H.tga]])
LSM:Register("statusbar", "ElvUI I", [[Interface\Addons\LMT\Statusbars\ElvUI I.tga]])
LSM:Register("statusbar", "ElvUI J", [[Interface\Addons\LMT\Statusbars\ElvUI J.tga]])
LSM:Register("statusbar", "ElvUI K", [[Interface\Addons\LMT\Statusbars\ElvUI K.tga]])
LSM:Register("statusbar", "ElvUI L", [[Interface\Addons\LMT\Statusbars\ElvUI L.tga]])
LSM:Register("statusbar", "ElvUI M", [[Interface\Addons\LMT\Statusbars\ElvUI M.tga]])
LSM:Register("statusbar", "ElvUI N", [[Interface\Addons\LMT\Statusbars\ElvUI N.tga]])
LSM:Register("statusbar", "ElvUI O", [[Interface\Addons\LMT\Statusbars\ElvUI O.tga]])
LSM:Register("statusbar", "ElvUI P", [[Interface\Addons\LMT\Statusbars\ElvUI P.tga]])
LSM:Register("statusbar", "ElvUI Q", [[Interface\Addons\LMT\Statusbars\ElvUI Q.tga]])
LSM:Register("statusbar", "ElvUI R", [[Interface\Addons\LMT\Statusbars\ElvUI R.tga]])
LSM:Register("statusbar", "Skullflower", [[Interface\Addons\LMT\Statusbars\Skullflower.tga]])
